In [1]:
import numpy as np

In [2]:
arr_list = [1, 2, 3, 4, 5]
arr = np.array(arr_list)

In [3]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr[3]

4

In [7]:
arr[:3]

array([1, 2, 3])

In [8]:
arr[2:3]

array([3])

In [9]:
arr[arr>3]

array([4, 5])